
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcuwbjwhojzpcgrnaeva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjdXdiandob2p6cGNncm5hZXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQxNDgsImV4cCI6MjA1OTY4MDE0OH0.hU0CtSNPo4niqVO-KLphq6dhMh8cSGlkuBi61qllnYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
